name: Moof
favicon: null
layout_spectrum: 1
typography_spectrum: 0.23173
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#371a16'
    - '#1dad4b'
    - '#f39b20'
    - '#e4516d'
  brandStrength: 1
  lightness: 0.961368904914707
  saturation: 0.9844827519264072
  rhythmicContrast: 0.5
purpose: []
